// Import the Router function from the express module
import {Router} from 'express'

// Create a new router instance
const router = Router()

// Import all the trainer controller functions
import * as trainerController from './trainers.controllers.js'

// Define the routes and associate them with corresponding controller functions

// Route to add a new trainer
router.post('/addtrainer', trainerController.addTrainer) 

// Route to get all trainers along with their members
router.get('/getalltrainerswithmembers', trainerController.getTrainerWithMembers) 

// Route to get a specific trainer by their ID
router.get('/gettrainerbyid/:id', trainerController.getTrainerById) 

// Route to calculate the revenues generated by a specific trainer by their ID
router.get('/trainerrevenues/:id', trainerController.trainerRevenues) 

// Route to update a trainer's data by their ID
router.put('/updatetrainer/:id', trainerController.updateTrainer)

// Route to delete a trainer from the database using their ID
router.delete('/deletetrainer/:id', trainerController.deleteTrainer) 

// Export the router instance for use in other parts of the application
export default router